# Generated by Django 5.2.17 on 2026-09-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.loan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SETTLEMENT', 'Settlement'), ('LOAN_PAYMENT', 'Loan Payment')], default='EXPENSE', max_length=20),
        ),
    ]
