# Generated by Django 5.2.17 on 2026-09-05 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_loan_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('account', models.OneToOneField(limit_choices_to={'account_type': 'CREDIT_CARD'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='finance.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
