# Generated by Django 5.2.17 on 2026-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SETTLEMENT', 'Settlement'), ('LOAN_PAYMENT', 'Loan Payment'), ('CARD_PAYMENT', 'Card Payment')], default='EXPENSE', max_length=20),
        ),
    ]
